### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by matthewjporter** [badguy99/octoblock#14]
Hi, Would you know how to send a notification at say 9am what the best 2 hour slot would be for the remainder of the day?

**Comment by badguy99** [comment]
It should be possible to do this with Home Assistant Automations.
e.g. set up a trigger for 9am (I have one for backups at 2:30) - 
![image](https://user-images.githubusercontent.com/61918526/95135349-2be8e100-075c-11eb-99af-74921aee19b3.png)

Then, assuming you have an mobile phone set up with the home assistant app, set the automation to send it a notification. Set up an Action, with action type = Call Service, Service = notify.your_mobile_phone and service data :=
```
data:
  subtitle: Best 2 hour block
message: >-
  The best 2 hour block is at: 
  {{now().fromisoformat((states("sensor.octopus_2hour_time"))[:-7]).time()}}
title: Agile Octopus
```

The weird bit takes the value of sensor.octopus_2hour_time:
2020-10-06T00:30:00 BST

removes the last 7 characters:
2020-10-06T00:30

And converts from iso format into an object that I think the notification system gives out sensibly - I haven't looked at this for a while, but I think this is right - I used to use it for setting dishwasher time, but my trigger, which isn't time based, is broken at the moment, so haven't used it for a while.

**Comment by matthewjporter** [comment]
Cheers, Will give it a go

**Comment by matthewjporter** [comment]
Thanks, That worked like a charm
