### ISSUE TITLE
Trigger Template Update

### ISSUE THREAD

**Issue by matthewjporter** [badguy99/octoblock#15]
The trigger used in your example does not seem to work, I landed up creating a sensor with the following value_template

`
value_template: >
  {% if states("sensor.date_time_iso") == (states("sensor.octopus_1hour_time")[:-4]) %}
    true
   {% else %}
     false
   {% endif %}
`
This allowed me to create automations based on specific time blockes on a sensor state that was "true" or "false" and guessing this would work just as a trigger in an automation

My entire sensor is

`
- platform: template
  sensors:
    bestihourslot:
      friendly_name: Best 1 Hour Slot
      value_template: >
        {% if states("sensor.date_time_iso") == (states("sensor.octopus_1hour_time")[:-4]) %}
          true
        {% else %}
          false
        {% endif %}
`

**Comment by badguy99** [comment]
Thanks, I've updated the readme, things had moved on in home assistant since I originally wrote that - it reflects what I am using now.
