### ISSUE TITLE
Non-Contiguous Time slots

### ISSUE THREAD

**Issue by d1964b** [badguy99/octoblock#19]
Can Octoblock be updated to identify a non-contiguous set of time slots that sum to a defined time length ? Let me explain, like many people I have a set of devices which I want to power for 'n' minutes in a certain time window but I don't need those time slots to be contiguous, these happen to be my big users of power i.e. hot water immersion tank , electrical storage heaters etc. 
I imagine the soultion looking something like this:

blocks:
    - durationMinutes: 60      
      slotwidthMinutes: 30     
      start_period: today
      name: ImmersionTank
      limits:
        start_time: '05:00'
        end_time: '07:00'

which would return - possibly as an array- the two cheapest time slots within the four available in the time window given that 'slotwidth'.I don't know how well HA handles array values or even if HA/python has an Ismember type function that you could easily call in your automations condition to return a boolean value Alteratively you could create a set of entities based on the name each representing a time slot ( ImmersionTank1 and ImmersionTank2 - in this case ) that you could then refer to using the documented syntax. Thanks a lot - I know it might sound self serving - but I think this would meet a widespread need.

**Comment by badguy99** [comment]
I believe this is available in https://github.com/markgdev/home-assistant_OctopusAgile already, as such I'm not looking to develop it myself. But if you want to put up a pull request for review, I'll happily look at it and add it in.
