### ISSUE TITLE
Can't see this in HACS

### ISSUE THREAD

**Issue by mdeakin99** [badguy99/octoblock#21]
This comes highly recommended by a few people on the Agile Chat in facebook.  I would love to install it but for some reason can't see it in HACS.  If i try and add it as a custom repository,  it wont let me.

Am I doing something wrong?

**Comment by badguy99** [comment]
Have you got AppDaemon installed within Home Assistant already (Supervisor -> Add on store)?
If so you should be able to find Octoblock from the Automations page of HACS...
![image](https://user-images.githubusercontent.com/61918526/110997389-3ba4cb00-8375-11eb-8f6a-43ee9fb0601f.png)

**Comment by mdeakin99** [comment]
So I checked and I didnt have 'Automation' as an option.  Did a bit of research and there is a setting in the HACS integration for enabling AppDaemon discovery.  Ticked that and its working fine.  Thanks!
