### ISSUE TITLE
Look ahead binary sensor - will price be below x in next n hours

### ISSUE THREAD

**Issue by badguy99** [badguy99/octoblock#4]
Just sketching this out at the moment, but I plan to add the following:

Add a binary sensor that will be set to true if the price will go below a certain point, n, within the next x hours, up to the maximum look ahead that Octopus Energy provide price data for.

e.g.
binary_sensor.octopus_below_n

Use case example:
If Octopus price is going below n, at some point in the near future, turn off gas fired hot water program, as immersion heater will be used when price goes below n instead. 

Current sensors don't cover this, they give current price or cheapest price for a certain length of time.

Things to consider:
When time period has passed that price was below low point, set back to false, but not if it will drop below low point again within the next x hours.

**Comment by jameshiscott** [comment]
Awesome idea, it would also be helpful to be able to say "below a avg price for the next x hours" as maybe you need a full hour to make it worth using. So this would not give you the cheapest time but in the next 4 hours you should use the immersion heater in 2 hours time for 1 hour as your boost.
